Repository MiniMiniBay/MiniMiniBay-backend, pull requests merged in 2024-04, with the labels that each got.

#3 [초기 설정] spring boot 초기 설정 완료
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mmbay/mmbay/MmbayApplication.java
  src/main/resources/application.yml
  src/test/java/com/mmbay/mmbay/MmbayApplicationTests.java
Labels: :tada: initial

#4 [초기 설정] spring boot 초기 설정 완료- main branch 병합
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mmbay/mmbay/MmbayApplication.java
  src/main/resources/application.yml
  src/test/java/com/mmbay/mmbay/MmbayApplicationTests.java
Labels: :tada: initial

#7 [Docs] Pull Request Template 수정
  .github/pull_request_template.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/mmbay/mmbay/MmbayApplication.java
  src/main/resources/application.yml
  src/test/java/com/mmbay/mmbay/MmbayApplicationTests.java
Labels: :memo: documentation

#8 [Docs] Pull Request Template 수정 - main branch 병합
  .github/pull_request_template.md
Labels: :memo: documentation

#9 [설정파일 수정] application.yml 수정
  src/main/resources/application.yml
Labels: :heavy_check_mark: PR

#10 [설정파일 수정] application.yml 수정 - main branch 병합
  src/main/resources/application.yml
Labels: :heavy_check_mark: PR
